---
title: "Field Recordings"
author: "Nilo Merino Recalde"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  github_document:
    toc: true
    toc_depth: 3
editor_options:
  chunk_output_type: console
---

```{r setup, include=TRUE, , message=FALSE}
# Requires: 
library(rprojroot)
library(tidyverse)
library(lubridate)
library(ggmap)
library(plotKML)

# Knitr settings: 
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = TRUE, fig.path = "../../reports/figures/")
```

```{r pkg, message=FALSE}
# Source file
source("./src/data-read/import-field-recordings.R")
```


### Read GPS coordinate of recording locations 
<span style="color:red">Note: This will change the names of newly added files to something more sensible</span>

```{r read}

# Gets filenames of GPS coordinates and .WAVs
# There should only be one .gpx file in this directory

file.gps <-
  list.files(path = "./data/raw/00_bagley",
             full.names = TRUE,
             pattern = ".gpx$") 

file.wav.new <-
  list.files(path = "./data/raw/00_bagley",
             full.names = FALSE,
             pattern = ".wav$") %>%
  grep(pattern = "_",
       inv = T,
       value = T) %>%
  sort(decreasing = FALSE)

file.wav.existing <-
  list.files(path = "./data/raw/00_bagley",
             full.names = FALSE,
             pattern = ".wav$") %>%
  grep(pattern = "_",
       inv = F,
       value = T) %>%
  sort(decreasing = FALSE)

# Imports and cleans gps coordinates

locations <-
  file.gps %>%
  plotKML::readGPX(
    waypoints = TRUE,
    bounds = FALSE,
    tracks = FALSE,
    routes = FALSE
  ) %>%
  pluck("waypoints") %>%
  as_tibble() %>%
  mutate(time = ymd_hms(time)) %>%
  mutate(filename = paste0(date(time), "_", str_sub(name, start = -3), ".wav")) %>%
  arrange(., time)

## Renames Zoom H4N files to something more sensible. Pause to think before using.

file.rename(from = file.wav.new, to = setdiff(locations$filename, file.wav.existing))
```

---

#### Check that gps and audio times and filenames are coherent

```{r check}

all.wav.files <-
  list.files(path = "./data/raw/00_bagley",
             full.names = TRUE,
             pattern = ".wav$") %>%
  grep(.,
       pattern = "_",
       inv = F,
       value = T) %>%
  sort(., decreasing = FALSE)

all.wav.files.metadata <-
  file_metadata(all.wav.files) %>% select(
    .,
    -exif_tool_version,
    -file_type,
    -mime_type,
    -description,
    -originator_reference,
    -bwf_version,
    -coding_history
  ) %>%
  mutate(time = ymd_hms(date_time_original))


# Check that gps and audio times are coherent: look for possible mistakes when
# manually labelling POIs in the field. Execution will halt if there are any duplicates.
# For other issues, check plots.

if ('TRUE' %in% duplicated(locations$filename)) {
  stop("There is a duplicated entry in the .gpx data file")
} else {
  print("There are no duplicates in the .gpx gps data file")
}

if ('TRUE' %in% duplicated(all.wav.files.metadata$file_name)) {
  stop("There is a duplicated audio file. Check and fix before continuing")
} else {
  print("There are no duplicated audio files")
}


# One way to remove duplicates is 'my_data %>% distinct()'.
# Note that this removes the second entry, which might not be what you want.

locations <- locations %>% distinct(filename, .keep_all = TRUE)

time.diff <-
  tibble(
    time.diff = as.numeric((
      all.wav.files.metadata$time - locations$time
    ) / 60),
    filename = all.wav.files.metadata$file_name,
    day = yday(all.wav.files.metadata$time)
  ) %>%
  ggplot(aes(x = filename, y = time.diff)) +
  geom_point() +
  facet_grid(rows = vars(day)) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Difference between audio creation time and gps entry time",
       subtitle = "Look for outliers!",
       x = element_blank(),
       y = "Time difference (mins)")

ggsave(
  time.diff,
  path = "./reports/figures",
  filename = "01_time-difference.png",
  width = 20,
  height = 20,
  units = "cm",
  dpi = 350
)
```

<br>

```{r fig1, out.width = "90%", fig.align="center", message=FALSE, warning=FALSE, echo=FALSE}
time.diff 
```

---

### Map recording locations

```{r mapcode, message=FALSE}

## This is my google key, remove before sharing
#ggmap::register_google(key = "AIzaSyDfAbhsGQ32byJTmQnpOFjQ_5yr3ViVYeI", write = TRUE)

bagley.wood <- c(lon = -1.259911, lat = 51.715711)

# # Satellite map
# get_googlemap(
#   center = bagley_wood,
#   zoom = 14,
#   scale = 4,
#   maptype = "terrain",
#   color = "color"
# ) 

bagley.samples.map <- 
  get_map(
    location = bagley.wood,
    source = "stamen",
    maptype = "terrain",
    crop = FALSE,
    zoom = 15
  ) %>%
    ggmap(base_layer = ggplot(aes(x = lon, y = lat), data = locations)) %>%
    +stat_density_2d(
      aes(fill = ..level..),
      geom = "polygon",
      alpha = .2,
      color = NA
    ) +
    scale_fill_gradient2(
      "Density",
      low = "white",
      mid = "yellow",
      high = "red",
      midpoint = 12000
    ) +
    geom_point(colour = "black", size = 2)


# Save plot

ggsave(
  bagley.samples.map,
  path = "./reports/figures",
  filename = "00_bagley-map.png",
  width = 20,
  height = 20,
  units = "cm",
  dpi = 350
)

```

<br>

```{r fig2, out.width = "90%", fig.align="center", message=FALSE, warning=FALSE, echo=FALSE}
bagley.samples.map
```

