---
title: "Recording great tit songs"
description: |
  An exploration of the factors that affect recording success (for the transfer report)
author:
  - name: Nilo M. Recalde
    url: https://zoology.web.ox.ac.uk/people/nilo-merino-recalde
    affiliation: Department of Zoology
    affiliation_url: https://example.com/spacelysprokets
date: "`r Sys.Date()`"
output: distill::distill_article
editor_options:
  chunk_output_type: console
---
```{r setup}
# Knitr settings: 
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, cache = TRUE)
options(scipen = 999)
```
# Import libraries
```{r library}
library(tidyverse)
library("gridExtra")
# Knitr settings: 
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = TRUE, fig.path = "../../reports/figures/")
```

```{r pkg, message=FALSE}
# Source file
# source()
```

# Load dataset
<span style="color:red">Note: This is an example</span>

```{r laod data}
dataset_name <-  "GRETI_HQ_2020_segmented"
year = "2020"

data_dir <-  file.path(getwd(), "data", "resources", dataset_name)
figures_path <- file.path(getwd(), "reports", "text", "talks")
datafile <- file.path(data_dir, "avg_IOIs.csv" )
dataset <-  read_csv(datafile)
```

# Plot IOIs
```{r}

IOIs_plot = 
dataset %>% ggplot(aes(x=x, y=y)) + 
  geom_density_2d_filled(alpha = 1, contour_var = 'ndensity', bins=20) +
  # geom_jitter(size=0.1, colour='white', alpha=0.2, width = 0.015, height = 0.015) +
  geom_abline(intercept = 0.05, linetype=3, colour='white', size=0.6, alpha=0.6) +
  geom_abline(intercept = 0, linetype=1, colour='white', size=0.6, alpha=0.2) +
  geom_point(shape=3, aes(x=0.2, y=0.25), colour="red", size =4) +
  geom_point(shape=3, aes(x=0.124, y=0.174), colour="red", size =4) +
  #scale_x_continuous(breaks = c(0.1, 0.2, 0.3)) +
  #scale_y_continuous(breaks = c(0.5, 0.15, 0.25, 0.35)) +
  scale_fill_viridis_d("City\nCenter", option = "inferno") +
    labs(y = 'Second interval (s)\n',
       x = "\nFirst interval (s)",
       title = "Rhythmic intervals in great tit song") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(
    #panel.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.ticks.y = element_blank(),
    axis.ticks.x = element_blank(),
    legend.position = "none",
    text = element_text(size=15)
  ) +
  coord_equal(xlim=c(0.074,0.35),ylim=c(0.07,0.35))

IOIs_plot
ggsave(file=file.path(figures_path, "IOIs.svg"), plot=IOIs_plot, width=6, height=6, device = 'svg')


dataset %>% ggplot(aes(x=x, y=y)) + 
  geom_point()


dataset %>% ggplot(aes(x=x, y=y)) + 
  stat_density_2d(aes(fill = ..level..), geom = "polygon", colour="white") +
  #stat_density_2d(aes(fill = ..density..), geom = "raster", contour = FALSE) +
  #geom_bin2d(bins=50) + 
  scale_fill_viridis_c("City\nCenter", option = "plasma") +
  coord_equal(xlim=c(0.05,0.5),ylim=c(0.05,0.5)) + 
  geom_abline(intercept = 0, fill='w') +
  geom_abline(intercept = 0.05)

dataset %>% ggplot(aes(x=x, y=y)) + 
  geom_density_2d( size=2) +
  scale_color_viridis_c() +
    coord_equal(xlim=c(0.05,0.5),ylim=c(0.05,0.5)) + 
  geom_abline(intercept = 0) +
  geom_abline(intercept = 0.05)


dataset %>% ggplot(aes(x=x, y=y)) + 
  stat_density_2d(geom = "polygon",
                  aes(alpha = ..level..),
                  bins = 10) +
  coord_equal(xlim=c(0.05,0.5),ylim=c(0.05,0.5)) + 
  geom_abline(intercept = 0) +
  geom_abline(intercept = 0.05)
+

```



