---
title: "Recording great tit songs"
description: |
  An exploration of the factors that affect recording success (for the transfer report)
author:
  - name: Nilo M. Recalde
    url: https://zoology.web.ox.ac.uk/people/nilo-merino-recalde
    affiliation: Department of Zoology
    affiliation_url: https://example.com/spacelysprokets
date: "`r Sys.Date()`"
output: distill::distill_article
editor_options:
  chunk_output_type: console
---
```{r setup}
# Knitr settings: 
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, cache = TRUE)
options(scipen = 999)
```
# Import libraries
```{r library}
library(tidyverse)
library("gridExtra")
#library(ggtern)
# Knitr settings: 
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = TRUE, fig.path = "../../reports/figures/")
```

```{r pkg, message=FALSE}
rm(list = ls())
x <- gc()
x <- c(
    "parallel",
    "vegan",
    "bioacoustics",
    "warbleR" ,
    "ggplot2",
    "Rraven",
    "cluster",
    "randomForest",
    "MASS",
    "fossil",
    "pbapply",
    "adehabitatHR",
    "Sim.DiffProc",
    "caret",
    "e1071",
    "tidyverse"
  )

# load packages 
aa <- lapply(x, function(y) {
  if (!y %in% installed.packages()[, "Package"])  {
    install.packages(y)
  }
  try(require(y, character.only = T), silent = T)
})

```

# Load dataset
<span style="color:red">Note: This is an example</span>

```{r laod data}
root.dir = rprojroot::find_rstudio_root_file()
dataset_name <-  "GRETI_HQ_2020_notes"
data_dir <-  file.path(root.dir, "data", "processed", dataset_name, 'WAV')
out_dir = file.path(root.dir, "data", 'note_dfs', dataset_name)
est.file.name <- file.path(out_dir, 'selection_table.RDS')
ncores = parallel::detectCores() - 1
load(est.file.name)

# WarbleR options
warbleR_options(
  wav.path = data_dir,
  f = 32000,
  wl = 512,
  flim = c(1.2, 8),
  ovlp = 95,
  bp = c(1.2, 8),
  parallel = ncores
)

# figures_path <- file.path(getwd(), "reports", "text", "talks")
```

# Plot IOIs
```{r}
# Measure spectral parameters
sp <- specan(est, parallel=ncores, threshold = 15)
```

```{r}
# Concatenate data
parameters = sp %>% add_column(note = acous.meas[, 1], .before = 1)
sp$note <-
  lapply(sp$sound.files, function(x)
    gsub("\\..*", "", x))

df_list = list()
for (i in 0:2) {
  df_list[[as.character(i)]] = sp %>% filter(str_detect(note, paste0(i, "$"))) %>% 
    rename_at(vars(-note), ~ paste(.x, as.character(i), sep = "_")) %>% 
    mutate(note = gsub('-[^-]*$', '', note))
}

parameters =  df_list %>% reduce(left_join, by = "note") %>% drop_na()
parameters = parameters %>% mutate(diff=abs(abs(meandom_0) - abs(meandom_1))) %>% mutate(ratio1 = meandom_0 / meandom_1, ratio2 = meandom_1 / meandom_2)


sp$key <-lapply(sp$sound.files, function(x) gsub("\\..*", "", x))
spdata = sp %>% mutate(seqposition = str_split_fixed(sp$key, "-", 4)[,4], bird= str_split_fixed(sp$key, "-", 4)[,1], songtype= str_split_fixed(sp$key, "-", 4)[,2])
```

```{r}


spdata %>% ggplot(aes(x=meandom, fill=seqposition)) + 
  geom_density(adjust = 0.5, alpha=0.7, colour=NA) + 
  coord_fixed(5) +
  scale_fill_manual(values = c('#cf4446', '#4b0c6b', '#f7d03c'), name='Note\nposition', labels = c("First", "Second", "Third")) +
  theme(
    panel.background = element_rect(fill = '#f2f1f0', colour = NA),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.ticks.y = element_blank(),
    axis.ticks.x = element_blank(),
    text = element_text(size=15),
    aspect.ratio=1
  )

parameters %>% ggplot(aes(x=ratio1, y=ratio2)) + geom_point()


freq_plot = parameters %>% ggplot(aes(x=meandom_1, y=meandom_0)) + 
  geom_density_2d_filled(alpha = 1, contour_var = 'ndensity', bins=20) +
  # geom_point(size=0.1, colour='white', alpha=0.2) +
  geom_abline(intercept = 0, linetype=1, colour='white', size=0.6, alpha=0.2) +
  geom_abline(intercept = 0.8, linetype=3, colour='white', size=0.6, alpha=0.6) +
  geom_abline(intercept = -0.8, linetype=3, colour='white', size=0.6, alpha=0.6) +
  geom_point(shape=3, aes(x=3.5, y=4.3), colour="red", size =4) +
  geom_point(shape=3, aes(x=4.15, y=3.35), colour="red", size =4) +
  scale_fill_viridis_d("City\nCenter", option = "inferno") +
  labs(y = 'Second frequency (kHz) \n',
       x = "\nFirst frequency (kHz)",
       title = "Melodic intervals in great tit song") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(
    panel.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.ticks.y = element_blank(),
    axis.ticks.x = element_blank(),
    legend.position = "none",
    text = element_text(size=15)
  ) +
  coord_equal(xlim=c(2.7,6),ylim=c(2.7,6))

freq_plot
ggsave(file=file.path(figures_path, "freq_plot.svg"), plot=freq_plot, width=6, height=6, device = 'svg')

IOIs_plot = parameters %>% ggplot(aes(x=meandom_0, y=meandom_1)) + 
  geom_density_2d_filled(alpha = 1, contour_var = 'ndensity', bins=10) +
  coord_equal(xlim=c(0.06,0.34),ylim=c(0.06,0.34)) + 
  #geom_abline(intercept = 0.05, linetype=3, colour='white', size=1, alpha=0.4)+
  #geom_point(shape=3, aes(x=0.2, y=0.25), colour="black", size =4) +
  #geom_point(shape=3, aes(x=0.124, y=0.174), colour="black", size =4) +
  #scale_x_continuous(breaks = c(0.1, 0.2, 0.3)) +
  #scale_y_continuous(breaks = c(0.5, 0.15, 0.25, 0.35)) +
  scale_fill_viridis_d("City\nCenter", option = "inferno") +
    labs(y = 'Next note interval\n',
       x = "\nNote interval",
       title = "Rhythmic ratios in great tit song") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(
    panel.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.ticks.y = element_blank(),
    axis.ticks.x = element_blank(),
    legend.position = "none",
    text = element_text(size=15)
  )
IOIs_plot


parameters %>% ggtern(aes(x=meandom_0,y=meandom_1, z=meandom_2)) +
  stat_density_tern(geom='polygon', aes(fill=..level..), bins=100) +
  geom_point(size=0.1, colour='white', alpha=0.03) +
  labs(title="Caca, 2015") +
  scale_fill_viridis_c("City\nCenter", option = "inferno") +
  # theme_rgbw() +
  tern_limit(T = 0.6, L = 0.6, R = 0.6) +
  theme(
    panel.background = element_rect(fill = 'black', colour = NA),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.ticks.y = element_blank(),
    axis.ticks.x = element_blank(),
    legend.position = "none",
    text = element_text(size=15)
  )







ggsave(file=file.path(figures_path, "IOIs.svg"), plot=IOIs_plot, width=10, height=10)


dataset %>% ggplot(aes(x=x, y=y)) + 
  geom_point()


dataset %>% ggplot(aes(x=x, y=y)) + 
  stat_density_2d(aes(fill = ..level..), geom = "polygon", colour="white") +
  #stat_density_2d(aes(fill = ..density..), geom = "raster", contour = FALSE) +
  #geom_bin2d(bins=50) + 
  scale_fill_viridis_c("City\nCenter", option = "plasma") +
  coord_equal(xlim=c(0.05,0.5),ylim=c(0.05,0.5)) + 
  geom_abline(intercept = 0, fill='w') +
  geom_abline(intercept = 0.05)

dataset %>% ggplot(aes(x=x, y=y)) + 
  geom_density_2d( size=2) +
  scale_color_viridis_c() +
    coord_equal(xlim=c(0.05,0.5),ylim=c(0.05,0.5)) + 
  geom_abline(intercept = 0) +
  geom_abline(intercept = 0.05)


dataset %>% ggplot(aes(x=x, y=y)) + 
  stat_density_2d(geom = "polygon",
                  aes(alpha = ..level..),
                  bins = 10) +
  coord_equal(xlim=c(0.05,0.5),ylim=c(0.05,0.5)) + 
  geom_abline(intercept = 0) +
  geom_abline(intercept = 0.05)
+

```



