---
title: "Transfer of Status Report" 
author: Nilo M. Recalde
supervisors: Professor Ben Sheldon and Dr. Ella Cole
date: "Last compiled on `r format(Sys.time(), '%d %B, %Y')`"
link-citations: true
secnumdepth: 1
numbersections: false
toc: true
lof: true
strip-comments: true
urlcolor: #5e3100
linkcolor: #5e3100
documentclass: report
output:
   pdf_document:
     latex_engine: xelatex
header-includes:
  - \usepackage{fontspec}
  - \setmainfont[Ligatures=TeX,Scale=1]{Lato}
  - \usepackage{leading}
  - \leading{18pt}
  - \usepackage{sectsty} 
  - \chapterfont{\raggedleft}
bibliography: library.bib
csl: animal-behaviour.csl

---

# Introduction

\hfill *Definitely not a placeholder for a Darwin quote*

## General introduction

### Animal culture and social learning

Culture was once considered the sole domain of humans. Over the past few decades this view has been steadily challenged, and today it is common to find allusions to non-human animal cultures in scientific journals and the popular press alike. To be sure, some energetically oppose the notion, and there is no shortage of disagreement over the very definition of the term ‘culture’. But an increasing number of students of behaviour and evolution suspect that, intricate and distinctive as human culture might be, the difference must be one of degree—not kind.

What constitutes culture, then? For our purposes, we can define it as any behavioural trait that is maintained in a population by virtue of being learnt from others; not genetically inherited, nor individually acquired. [see definitions in @Whiten2017; @Laland2003.] Human ritual funerary practices are cultural, so is the game of croquet. And, under this definition, so are tool use in capuchin monkeys, homing efficiency in pigeons, the songs of many birds, some feeding behaviours in humpback whales, and even mate preferences in fruit flies [@Falotico2019; @Sasaki2017a; @Slater2003; @Allen2013a; @Thornquist2019].

Social learning is ubiquitous among animals, and a prerequisite for culture. Although it may not always be beneficial [@Giraldeau2002; @Whitehead2009; @Henrich1998], there is ample evidence that many of the things that many animals must learn to survive and reproduce can only be acquired by observing or interacting with others [@Galef2005]. Learning will happen more often from animals that are closer in space or in a social group, and this inevitable fact creates opportunities for behaviours to change differently in different populations, sometimes becoming better suited to local conditions. When these differences—beneficial or not—accumulate and persist over time, a cultural tradition is born.

Whether found in humans or other animals, cultures can be transient or long-lasting, disorderly diverse or monolithically uniform. To give two primate examples, chimpanzees (*Pan troglodytes*) may have used stone tools in a similar way for thousands of years [@Mercader2007; @Carvalho2008], and white-faced capuchin monkeys (*Cebus capucinus*) frequently invent and abandon quirky social conventions such as eyeball-poking, handsniffing and tail-sucking [@Perry2003].

### Cultural evolution in birds

[For a recent review see @Aplin2018]

Socially learned acoustic signals, such as the song of humpback whales and oscine songbirds, offer incredibly valuable opportunities for answering some of these questions. Songs can convey information about the identity and social position of signallers; they are moulded by natural and sexual selection, stochastic change and cultural processes, and, crucially, can be recorded and analysed in minute detail. 

Building on a rich tradition of research into passerine song, recent methodological and theoretical advances 21,31,32 have made it possible to study innate structural biases 10,33 and conformist biases 24 in song learning, spatial variation in repertoire sharing and novelty, timing of song acquisition in the wild 36 , relationships between singing rate, personality and territoriality, and song structure and syntax .

Across bird taxa, the importance of social learning for song production is sparse, and the size of the repertoire thus acquired varies greatly . Among the obligate social learners, species whose songs are not exclusively transmitted from father to offspring provide an excellent opportunity to gain a more nuanced understanding of the many factors shaping the evolution of cultural traits.

… why song is great to study this: here comes a brief intro to song.

## Bird song: a short introduction

#### Historical

Brief introduction to the long history of the study of bird song. Barrington, Marler, Thorpe, Nottebohm, etc.

#### Why sing?

Overview of some of the hypothesised ultimate causes behind the evolution of singing in birds, and some of the functions that it may serve in different taxa.

#### Song learning in phylogenetic perspective

Most birds vocalise, but song learning has only evolved in three orders (Psittaciformes, Apodiformes, and Passeriformes). Within the passerines, oscines learn their songs, while suboscines do not. Briefly, why might social acquisition of song evolve?

## (Some of) The forces that shape bird song

#### Ecological factors

#### Physiological constraints and phylogenetic inertia

#### Sexual selection

#### Cultural transmission dynamics

#### The interplay of innate constraints and social learning

A brief discussion contrasting a) the emphasis placed by some authors on high-fidelity learning with b) ideas more along the lines of Heyes and the french in explaining cultural stability (of song). 

Also briefly introduce the experiments of Tchernichovski, Feher et al in light of ideas about convergent transformation, and @Mets2019a, @James2020



>  That universal acoustic patterns are observed in the songs of both untutored and early-deafened birds highlights the contribution motor production biases to the emergence of universals in culturally transmitted behaviors. [@James2020]

> The findings thus suggest that tailoring instruction to suit an individual's natural learning tendencies – which depend on their genes – can enhance learning. [@Mets2019a]

#### Spatial, social and demographic factors, how they affect songs ( and learning opportunities) in birds



#### Song design and natural variation of song;  constraints and polymorphic cultures



## Introduction to the study system

#### Great tits

Great Tits, Parus major L., are one such species. Their repertoire consists of 1 to 8 phrases, or song types, that they learn from conspecifics—primarily during their first year of life, until they have established a territory. Male great tits are more likely to share song types with neighbouring breeding males than with their fathers, and similarity in their songs and repertoire novelty and size are known to be influenced by spatial and demographic factors . 

However, despite a wealth of studies on great tit song, the mechanisms that govern its learning and variation remain unclear. Furthermore, characterisation of their features has been generally limited to a few acoustic and temporal parameters that may not be of great biological relevance 



#### Precedents: 

#### Krebs et al., Fayet 2014



## Concrete aims

What I am actually going to do, specific questions to answer.





# Methods

## Study system

The study was carried out in Wytham Woods, Oxfordshire, UK (51°46′N, 1°20′W). Wytham woods is a semi-natural deciduous woodland, around 415 hectares in extension, which is surrounded by farmland. Here, a population of great tits is monitored as part of a long-term survey that began in 1947. The majority of great tits nests in nestboxes with know locations. Every year, fieldworkers record the identities of breeding males and females, the dates of clutch initiation and egg hatching, clutch size, and fledgling success under standardised protocols. A large proportion of birds in the population are fitted with a unique British Trust for Ornithology (BTO) metal leg ring either as nestlings or as adults. During the breeding season, from March to June, great tit pairs are socially monogamous and defend territories around their nestboxes [@Hinde1952].

## Song recording

Every nestbox in the study site is checked by fieldworkers at least once a week before and during egg laying, which can last from one to 14 days [@Perrins1965]. When a nestbox was marked as having great tit activity, which usually coincided with the laying of the first eggs, I placed an autonomous sound recorder in the vicinity of the nestbox—either in the same tree or in a suitable neighbouring tree. I recorded birds in this manner from early April until mid-May, leaving each recorder in the same location for three consecutive days before moving it to a different nestbox. I relocated ten recorders every day throughout the duration of the recording period.

I used 30 AudioMoth recorders  [@Hill2019b], which were housed in waterproof, custom-built enclosures (See Fig X). Recording began approximately one hour before sunrise (~ 05:36 – 04:00 UTC) and consisted of seven 59-minute-long recordings with a sample rate of 48 kHz.

## Definitions

There is not a consistent set of terms used to refer to the different levels at which the acoustic output of a bird can be described. For clarity, these are the definitions that I use throughout this work:

| Term          | Definition                                                   |
| :------------ | :----------------------------------------------------------- |
| **Note**      | A single uninterrupted vocalisation; the smallest unit of analysis |
| **Phrase**    | The smallest set of different notes that are repeated stereotypically |
| **Song**      | One or more repeated phrases, preceded and followed by silences of a duration exceeding that of the longest silence between each note in a phrase |
| **Song bout** | A set of one or more songs that are preceded and followed by silences longer than 10 seconds. I will change this to a probabilistic definition based on the distribution of silence durations; typically a more or less arbitrary threshold is used but I’d rather have a better grounded definition |

## Audio analysis

### Pre-processing and segmentation

#### Song segmentation

I inspected spectrograms for each raw recording aided by AviaNZ, an open-source Python program written by Marsland and colleagues [@Marsland2019].  I selected songs based on a simple criterion: that its notes were clearly distinct from background noise and other bird vocalisations. I chose entire songs where it was possible; where it was not, I selected the longest contiguous segment available.

I included songs produced from approximately one hour before sunrise to four hours after sunrise for each bird and day. If a 59-min recording solely contained rain or wind I also included the following 59-min recording.

#### Assigning song bouts to individuals

As a consequence of the automated nature of the recording process, there is a small chance that some of the songs recorded in the immediate vicinity of a given nest box do not belong to the focal bird. To minimise the chance of false positives, I discarded recordings with more than one vocalising bird if one was not distinctly louder than the rest. I also discarded all songs with a maximum amplitude below $-16$ dB, calculated as $20\log_{10}(\frac{A}{A_0})$, with $A= 5000$ and $A_0=32767$ (the maximum value for 16-bit digital audio). This threshold derives from the observation that, in those cases where there are simultaneous recordings of several immediate neighbours, an amplitude cutoff greater than 4000 always separates a focal bird from its nearest neighbours. Note that these are not calibrated values and are, therefore, relative to the recording equipment and settings I used—as well as other factors like sound directionality and vegetation cover.

#### Note segmentation

I segmented the resulting song selections into their constituent notes using a dynamic threshold algorithm implemented by @Sainburg2019b. Briefly, the algorithm finds minima in the spectral envelope of an spectrogram, which are considered silences; if the length of the signal between these minima exceeds a maximum note duration, a new local minima is defined that divides the signal in two shorter segments. This is repeated until multiple notes are defined or there are no local minima below a maximum amplitude threshold. Then, segments below a minimum note duration threshold are discarded. The minimum and maximum syllable length thresholds were determined by segmenting a small subset of songs (n = 30) with Chipper, an open-source, Python-based software developed by @Searfoss2020.

**Note**: I am currently working on implementing a segmentation algorithm that deals better with reverberation. Sometimes the previous note overlaps with the next and the current algorithm fails to separate them.

#### Spectrograms

I created spectrograms for each individual note in the dataset (See Fig X) from its normalised and band-passed waveform. I then log-scaled each spectrogram and clipped all values within the fifth lowest percentile, to remove background noise of low amplitude. I then zero-padded each spectrogram with length below the longest syllable, and built a dataset containing the metadata for each note and its spectrogram.

### Dimensionality reduction and clustering

#### At the population level

I prepared a $N × d$-dimensional array, with $N =$ total number of syllables in the dataset and $d = 64 × 132$,  the length of a flattened two-dimensional spectrogram array. I then projected this array onto a low-dimensional embeddings found using UMAP (Uniform Manifold Approximation and Projection, [@McInnes2018] ) and PHATE  (Potential of Heat-diffusion for Affinity-based Trajectory Embedding, [@Moon2019]), two non-linear manifold learning and dimensionality reduction algorithms. Full details of the implementation and parameters can be found in the corresponding [code module](#code-availability).

#### For individual birds

In a similar way, I used UMAP to project every note sung by each bird onto a lower-dimensional space. Specifically, I created a two-dimensional projection for visualisation and a ten-dimensional projection for clustering. I then used the latter to infer the note types sung by each bird, by finding areas occupied more densely within the acoustic space using HDBSCAN [@McInnes2017]

**Note:** I am currently defining ‘hard’ clusters, where notes are labelled as either clusters or noise. This makes some clusters a little bit noisy. I might try to implement ‘fuzzy’ clustering, where cluster memberhip is defined by probability vectors, and deal more strictly with outliers.

### Inferring syllable transitions

### Measuring acoustic distance

## Code availability:

The code necessary to reproduce all the analyses and figures in this report, along with more details about each method employed here, is available as an installable Python package from [github.com/nilomr/0.0_great-tit-song](https://github.com/nilomr/0.0_great-tit-song). Note: this repository is not yet public; contact the author for access.

# Results and discussion

## Quantifying the 2020 dataset

###  Sampling

### Songs and syllables

#### Syllable transitions



## Spatial structure



# Data collection plan for 2021

# Outstanding Issues

# Thesis plan

## Introduction

This first chapter will provide a general background to the topic of song learning in birds. I will try to integrate ideas from three bodies of research that are sometimes disconected, namely laboratory studies of song ontogeny, 

A literature review with four main sections: i) Cultural evolution and song learning in birds, ii) the factors fostering and limiting song diversity from a cultural evolutionary perspective, ii.i) social learning and learning biases, iv) 

An introduction to the study system

## What do great tits sing?

An in-depth description of the variability and similarity of great tit songs, from an acoustic and information-theoretical perspective. transitions, etc

Establishing… blablabla

at wytham level and european level

## Learning biases

who are the tutors?

mets etc: repertoires maybe not inheritable, but how about tempo, frequency, etc?

are all songs created equal? some regions of space more dense?

## How do spatial and demographic factors influence song learning?

## Transmission fidelity and cultural reinvention of songs

how stable

## The function of songs

## Synthesis



# References