---
title: "Singing activity trohoughout the breeding season"
author: "Nilo Merino Recalde<br>"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  github_document:
    toc: true
    toc_depth: 4
editor_options:
  chunk_output_type: console
---
<br>

```{r setup}
# Knitr settings: 
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
options(scipen = 999)
```

```{r}
library(tidyverse)
library(janitor)
library(gganimate)
library(lubridate)
library(hms)


```

```{r}
# Paths
dataset_id = 'GRETI_HQ_2020_segmented'
data_path = file.path(getwd(), "data")
sheet_path = file.path(data_path,
                       "processed",
                       dataset_id,
                       "metadata",
                       paste0(dataset_id, '_metadata.csv'))
```

```{r}
data = read_csv(sheet_path)[, -1] %>% clean_names() %>% mutate(date = ymd(date)) %>% filter(date != "2020-03-29") %>% mutate(n = 1)
get_time <- function(time) {
  time %>%
    str_split(" ") %>%
    map_chr(2) %>%
    hms()
}
bin_5min <- function(x) {
    binned = strptime(x, "%H:%M:%S")  %>%  
    lubridate::round_date(., "5 minute") %>% 
    as_hms()
    return(binned[[1]])
}

data = data %>% rowwise() %>% mutate(min_5 = bin_5min(time))
times_df = data %>% group_by(min_5, date) %>% summarize(n = sum(n))
```

```{r}

cc <-
  scales::div_gradient_pal("#d64e0d", "#b3ae86", "#00707d", "Lab")(seq(0, 1, length.out =
                                                                         nrow(unique(data[c("date")]))))
plot = times_df %>%
  mutate(min_5 = as.POSIXct(min_5, origin = "2018-01-01", tz = "GMT")) %>%
  ggplot(aes(x = min_5, y = n, fill = as.factor(date))) +
  geom_col(width = 300) +
  scale_x_datetime(date_breaks = "2 hour", date_labels = "%H:%M") +
  scale_y_continuous(breaks = scales::pretty_breaks(n = 8)) +
  scale_fill_manual(values = cc) +
  labs(y = 'Number of songs\n\n',
       x = "\n\nTime of day",
       title = "Singing activity throughout the day\n\n") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(
    panel.background = element_rect(fill = '#f2f1f0', colour = NA),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.ticks.y = element_blank(),
    axis.ticks.x = element_blank(),
    legend.position = "none",
    axis.ticks.length = unit(.85, "cm"),
    axis.title.x = element_text(color='black',face='bold'),
    axis.title.y = element_text(color='black',face='bold'),
    text = element_text(size = 30),
    plot.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "cm")
  )

plot

animated_plot =
  plot +
  transition_time(date) +
  enter_grow() +
  enter_fade() +
  #view_follow(fixed_x = TRUE) +
  shadow_mark(alpha = 0.85, size = 3)

songif = animate(
  animated_plot,
  renderer = gifski_renderer(),
  nframes = 80,
  fps = 3,
  width = 1000,
  height = 700
)

```

```{r}
dataset_name <-  "GRETI_HQ_2020_segmented"
year = "2020"
data_dir <-  file.path(getwd(), "resources", "brood_data", year)
file_path = file.path(data_dir, 'ebmp_broods_20-01-2021.csv') #TODO: get all and select newest automatically

laydates_df = read_csv(file_path) %>% clean_names() %>% mutate(date = dmy(lay_date), n=1) %>% filter(species == 'g') %>% group_by(date) %>% summarize(n = sum(n))

```


```{r}
# add dates where there are songs but not eggs
laydata = full_join(tibble(date = sort(unique(times_df$date))), laydates_df, by='date') %>% filter(date %in% unique(times_df$date) )
laydata[is.na(laydata)] <- 0

cc <-
  scales::div_gradient_pal("#d64e0d", "#b3ae86", "#00707d", "Lab")(seq(0, 1, length.out =
                                                                         nrow(unique(data[c("date")]))))

layplot = laydata %>%  ggplot(aes(x = date, y = n, fill = as.factor(date))) +
  geom_col(width = 1,
           alpha = 1) +
  scale_x_date() +
  scale_y_continuous(breaks = scales::pretty_breaks(n = 8)) +
  scale_fill_manual(values = cc) +
  labs(y = 'First egg laid\n\n',
       x = "\n\nDate",
       title = "Singing activity throughout the day\n\n") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(
    panel.background = element_rect(fill = '#f2f1f0', colour = NA),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.ticks.y = element_blank(),
    axis.ticks.x = element_blank(),
    legend.position = "none",
    axis.ticks.length = unit(.85, "cm"),
    axis.title.x = element_text(color='black',face='bold'),
    axis.title.y = element_text(color='black',face='bold'),
    text = element_text(size = 30),
    plot.margin = margin(t = 0, r = 0, b = 0, l = 3, unit = "cm")
  )

layplot

layplot = layplot +
  transition_states(date,
                    transition_length = 1,
                    state_length = 1) +
  labs(title = 'Day: {closest_state}\n\n') +
  shadow_mark(past = TRUE,
              future = FALSE,
              alpha = 0.9)

laygif = animate(
  layplot,
  renderer = gifski_renderer(),
  nframes = 80,
  fps = 3,
  width = 700,
  height = 700
)

```


```{r}
library(magick)

a_mgif <- image_read(songif)
b_mgif <- image_read(laygif)

new_gif <- image_append(c(a_mgif[1], b_mgif[1]))
for(i in 1:80){
  combined <- image_append(c(a_mgif[i], b_mgif[i]))
  new_gif <- c(new_gif, combined)
}

new_gif


```

```{r}


plot =
  data %>% ggplot(aes(x = time, fill = as.factor(date))) +
  geom_histogram(binwidth = 300) + # 5 min bins
  scale_x_time() +
  scale_fill_manual(values = cc) +
  labs(y = 'Songs\n',
       x = "\nTime",
       title = "Singing activity thoughout the day") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(
    panel.background = element_rect(fill = '#f2f1f0', colour = NA),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.ticks.y = element_blank(),
    axis.ticks.x = element_blank(),
    legend.position = "none"
  )

animated_plot =
  plot + transition_time(date) +
  labs(title = "Day: {frame_time}") +
  #view_follow(fixed_x = TRUE) +
  shadow_mark(alpha = 0.3, size = 3) 
  
animate(animated_plot, renderer = gifski_renderer(), nframes = 27, fps = 1, width = 600, height = 300)

#TODO: include sunrise times, fix aesthetics
```
