---
title: "Fielwork resources"
author: "Nilo Merino Recalde<br>"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  github_document:
    toc: true
    toc_depth: 4
editor_options:
  chunk_output_type: console
---
<br>

```{r setup}
# Knitr settings: 
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
options(scipen = 999)
```

```{r}
source("./src/fieldwork/fieldwork-resources.R")
```


### Prepare lay date data for the years 2016 to 2020 

```{r message=FALSE, warning=FALSE}
# All data / song recording data
df.paths <- list.files(data_path, pattern = "ebmp_broods", full.names = TRUE)
datalist = list()

for (year in df.paths) {
  datalist[[year]] <- read_csv(year) %>%
    clean_names() %>% 
    mutate(
      lay_date = dmy(lay_date),
      nestbox = str_sub(pnum, 6),
      year = year(lay_date),
      plot_date = as.Date(format(lay_date, format="%m-%d"), "%m-%d")
      ) %>% 
    select(-lay_date_uncertainty)
}

data_2016_to_2020 <- bind_rows(datalist)
data_2020 <- as_tibble(datalist[[5]])

recorded_2020 <-
  read_excel(file.path(sheet_path, "already-recorded.xlsx")) %>%
  clean_names() %>% 
  mutate_at(c('x', 'y'), as.numeric) %>%
  filter(str_detect(nestbox, "Nestbox", negate = TRUE)) %>%
  mutate(move_by = ymd(move_by))

clean_dataset_2020 <- full_join(recorded_2020, data_2020) %>% 
  mutate(recorded = case_when(is.na(am) ~ "NO", !is.na(am) ~ "YES")) %>% 
  select(nestbox, recorded, everything())

# Specific round data

nilo_round_2020 <-
  read_sheet("1I1WXw55BckjETRZIb2MtlVBM7AP0ik7RV6N9O8Vhdug") %>%
  clean_names()

```


### Does the presence of recorders influence egg laying rates or clutch sizes?

#### Plot recorded vs not recorded

```{r }

# Blue tits
blue_tit <- plot_nest_data(clean_dataset_2020, "b", variable = "laying_rate", text_size = 16) +
plot_nest_data(clean_dataset_2020, "b", variable = "clutch_size", text_size = 16)

# Great tits
great_tit <- plot_nest_data(clean_dataset_2020, "g", variable = "laying_rate", text_size = 16) +
plot_nest_data(clean_dataset_2020, "g", variable = "clutch_size", text_size = 16)


plots <- list(blue_tit = blue_tit, great_tit = great_tit)

for (plot in names(plots)) {
  ggsave(
    plot = get(plot),
    filename = paste0("effect_of_recorders_on_", plot, ".png"),
    path = figures_path,
    width = 25,
    height = 13,
    dpi = 350,
    units = "cm",
    device = "png"
  )
}

```

#### Estimate the effect of the presence of recorders

```{r models}

g_laying_rate <- clean_dataset_2020 %>% filter(species == "g") %>%
  lm(laying_rate ~ recorded + as.factor(lay_date), data = .) %>% plot_recorder_model("Great tit laying rates")

g_clutch_size <- clean_dataset_2020 %>% filter(species == "g") %>%
  lm(clutch_size ~ recorded + as.factor(lay_date), data = .) %>% plot_recorder_model("Great tit clutch sizes")

b_laying_rate <- clean_dataset_2020 %>% filter(species == "b") %>%
  lm(laying_rate ~ recorded + as.factor(lay_date), data = .) %>% plot_recorder_model("Blue tit laying rates")

b_clutch_size <- clean_dataset_2020 %>% filter(species == "b") %>%
  lm(clutch_size ~ recorded + as.factor(lay_date), data = .) %>% plot_recorder_model("Blue tit clutch sizes")

b_laying_rate + b_clutch_size + g_laying_rate + g_clutch_size
```

### Plot expected adult catching

```{r}

catching <- nilo_round_2020 %>%
  filter(catch_adults != "1900-01-09",
         catching_needed != 'No' | is.na(catching_needed)) %>% 
  mutate(catch_adults = ymd(catch_adults)) %>% 
  drop_na(nestbox)

text_size = 15

catching %>%
  ggplot(aes(x = catch_adults)) +
  geom_histogram(
    binwidth = 1,
    alpha = 0.9,
    fill = "#b8911d",
    colour = "white"
  ) +
  theme_minimal(base_size = text_size) +
  stat_bin(aes(y=..count.., label=..count..), geom="text", vjust=-.5, binwidth = 1) +
  scale_x_date(breaks = scales::pretty_breaks(n = 20)) +
  theme(
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    axis.text.x = element_text(face = "bold", size = text_size - (text_size / 100 * 20)),
    axis.title = element_text(size = text_size - (text_size / 100 * 15)),
    plot.title = element_text(face = "bold", size = text_size + (text_size / 100 * 10)),
    plot.subtitle = element_text(color = "#424242",
                                 size = text_size - (text_size / 100 * 20))
  ) +
  labs(
    y = "Number of nests\n",
    x = element_blank(),
    fill = "Year",
    title = "Adult catching dates (Extra round)",
    subtitle = paste0(
      "n = ",
      nrow(catching),
      " nests",
      " as of ",
      as.character(today()),
      ". Calculated as hatch date + 11 days"
    )
  )


catching %>%
  select(nestbox,
         species,
         catch_adults,
         catching_needed,
         pit_tag_1,
         pit_tag_2,
         father,
         mother) %>%
  group_split(catch_adults)

catching %>%
  select(nestbox,
         species,
         ring_day) %>%
  group_split(ring_day)

```


### Plot histogram of laying dates since 2016

```{r message=FALSE, warning=FALSE}

text_size = 15

lay_plot <- data_2016_to_2020 %>%
  ggplot(aes(x = plot_date, fill = factor(year))) +
  geom_histogram(binwidth = 1,
                 alpha = 0.7,
                 position = "identity") +
  labs(
    y = "Number of nests\n",
    x = element_blank(),
    fill = "Year",
    title = "Laying dates",
    subtitle = "Great tits, 2016 - 2020",
    caption = "Size of bins = 1 day"
  ) +
  theme_minimal(base_size = text_size) +
  coord_fixed(ratio = 0.3) +
  scale_fill_jcolors("pal7") +
  theme(
    panel.grid.minor = element_blank(),
    axis.text = element_text(size = text_size - (text_size / 100 * 30)),
    axis.title = element_text(size = text_size - (text_size / 100 * 15)),
    plot.title = element_text(face = "bold", size = text_size + (text_size / 100 * 10)),
    plot.subtitle = element_text(color = "#424242",
                                 size = text_size - (text_size / 100 * 20)),
    plot.caption = element_text(size = text_size - (text_size / 100 * 40)),
    legend.text = element_text(colour = "black"),
    legend.title = element_text(colour = "black"),
    legend.position=c(.9,.55),
    legend.background = element_rect(fill = 'white', size = 0)
  ) +
  scale_x_date(
    date_breaks = "7 days",
    date_labels = "%B %d",
    limits = c(as.Date("2020-03-25"), as.Date("2020-06-07"))
  ) + geom_vline(xintercept = as.Date(today()), size = 0.3) +
  annotate(
    "text",
    x = today(),
    y = 75,
    label = as.character(today()),
    angle = 90,
    vjust = 1.3,
    hjust = .7,
    size = text_size - (text_size / 100 * 70)
  )

```

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.align='center'}
plot(lay_plot)
```

### How many males are identified in the nest?

```{r  message=FALSE, warning=FALSE}
# How many males ID'd in nest (total nests - non IDd males)
years <- 2016:2020
difference <- vector(mode = "numeric", length = length(years))
for (i in seq_along(years)) {
  IDmales <-
    (data_2016_to_2020 %>%
       filter(year == years[i]) %>%
       select('father') %>%
       count() %>%
       sum()
     ) -
    (data_2016_to_2020 %>%
       filter(year == years[i]) %>%
       select('father') %>%
       is.na() %>%
       sum()
     )
  difference[i] <- IDmales
}

print(difference) # each year
print(mean(difference)) # average # ID'd males

```

