---
title: "Explore breeding success data "
author: "Nilo Merino Recalde<br>"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  github_document:
    toc: true
    toc_depth: 4
editor_options:
  chunk_output_type: console
---
<br>

# Settings and paths
```{r setup}
# Knitr settings: 
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
options(scipen = 999)
```

```{r}
library(tidyverse)
library(janitor)
library(lubridate)
library(ggdist)
```

```{r}
# Paths
dataset_name = "GRETI_HQ_2020_segmented"
data_dir <-  file.path(getwd(), "data", "resources", dataset_name)
datafile <- file.path(data_dir, "full_dataset.csv" )
dataset <-  read_csv(datafile) %>% janitor::clean_names()

```

```{r}

# Time of first song
dataset$mean_first_song_time <- as.POSIXct(dataset$mean_first_song_time)
labels <- pretty(dataset$mean_first_song_time, 5)

dataset %>% 
  drop_na(n_notes) %>% 
  ggplot(aes(x=x, y=y, colour = mean_first_song_time)) + geom_point(size=3) +
  scale_color_gradient2(low = "#ff0000", mid = "#99ada2", high = "#0061c2", midpoint = as.numeric(mean(dataset$mean_first_song_time, na.rm=TRUE)) , na.value = NA, trans = "time") +
  theme(panel.grid = element_blank(), panel.background = element_rect(fill = '#454545', colour = '#454545'))
  

# N of note types
dataset %>% 
  drop_na(n_notes) %>% 
  ggplot(aes(x=x, y=y, colour = n_song_types)) + geom_point(size=3) +
  scale_color_gradient2(low = "#0061c2", mid = "#99ada2", high = "#ff0000", midpoint = 3 ) +
  theme(panel.grid = element_blank())


dataset %>% 
  drop_na(n_notes) %>% ggplot(aes(x=mean_chick_weight, y=n_song_types)) + geom_point(size=3) + geom_smooth()




dataset %>% 
  drop_na(n_notes) %>% filter(n_song_types > 0) %>% ggplot(aes(x=as.factor(n_song_types), y=num_fledglings)) + geom_point(size=3, alpha=0.1) + geom_violin() + geom_jitter(width = 0.2, height = 0.2, alpha = 0.5)

```

